In [1]:
import numpy as np

In [2]:
print(np.__version__) # numpy version

1.21.0


In [24]:
empty_array = np.empty((3,2)) # 全零矩陣 and 內存大小
print(empty_array,empty_array.size * empty_array.itemsize)

[[0. 0.]
 [0. 0.]
 [0. 0.]] 48


In [25]:
help(np.info(np.add)) # 函數幫助文黨

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [11]:
array1 = np.arange(10,50) # reverse
print(array1[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [29]:
array2 = np.array([[2,5,0,3,5,0],[2,5,0,3,5,0]])
print(np.where(array2 != 0)) # find index in conditions(val != 0)
print(np.nonzero(array2)) 

(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64), array([0, 1, 3, 4, 0, 1, 3, 4], dtype=int64))
(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64), array([0, 1, 3, 4, 0, 1, 3, 4], dtype=int64))


In [19]:
array3 = np.random.randint(1,11,size=(3,3)) # 隨機構造矩陣
print(array3,array3.max(),array3.min())

[[ 4  8  5]
 [10  6  1]
 [ 8 10  3]] 10 1


In [34]:
array4 = np.ones((5,5)) # 5*5 最外層0 內層1
# array4[0,0:] = 0
# array4[0:,0:1] = 0
# array4[0:,-1] = 0
# array4[-1:,0:] = 0
array4 = np.pad(array4,pad_width=2,mode='constant',constant_values = 0)
print(array4)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [39]:
array5 = np.random.randint(1,11,size=(6,7,8)) # 尋找第100個元素的索引
np.unravel_index(100,(6,7,8)) # 第幾個元素 矩陣

(1, 5, 4)

In [41]:
array6 = np.random.randint(1,11,size=(5,5)) # 規一化 每一個值-最小值/最大值-最小值
max_ = array6.max()
min_ = array6.min()
array6 = (array6-min_) / (max_-min_)
array6

array([[0.11111111, 0.33333333, 0.22222222, 0.66666667, 0.        ],
       [0.44444444, 0.44444444, 0.77777778, 0.55555556, 0.33333333],
       [1.        , 0.        , 0.22222222, 0.55555556, 0.        ],
       [0.        , 0.55555556, 0.77777778, 1.        , 1.        ],
       [0.66666667, 0.33333333, 0.22222222, 0.        , 1.        ]])

In [51]:
np.random.seed(0)
array7 = np.random.randint(1,11,3) 
array8 = np.random.randint(1,11,3) 
print(array7)
print(array8)
print(np.intersect1d(array7,array8)) # 找出兩array相同的值

[6 1 4]
[ 4  8 10]
[4]


In [54]:
yseterday = np.datetime64('today','D') - np.timedelta64(1,'D') #時間格式 今天 明天 昨天
today = np.datetime64('today','D')
tommorow = np.datetime64('today','D') + np.timedelta64(1,'D') 
print(yseterday)
print(today)
print(tommorow)

2021-07-15
2021-07-16
2021-07-17


In [55]:
# 一個月所有的天
np.arange('2017-10','2017-11',dtype='datetime64[D]')

array(['2017-10-01', '2017-10-02', '2017-10-03', '2017-10-04',
       '2017-10-05', '2017-10-06', '2017-10-07', '2017-10-08',
       '2017-10-09', '2017-10-10', '2017-10-11', '2017-10-12',
       '2017-10-13', '2017-10-14', '2017-10-15', '2017-10-16',
       '2017-10-17', '2017-10-18', '2017-10-19', '2017-10-20',
       '2017-10-21', '2017-10-22', '2017-10-23', '2017-10-24',
       '2017-10-25', '2017-10-26', '2017-10-27', '2017-10-28',
       '2017-10-29', '2017-10-30', '2017-10-31'], dtype='datetime64[D]')

In [56]:
# 得到一個數的整數部分
np.random.seed(0)
num = np.random.uniform(0,10,10)
print(np.floor(num))

[5. 7. 6. 5. 4. 6. 4. 8. 9. 3.]


In [57]:
# 構造一個數組 讓他不能改變
z = np.zeros(5)
z.flags.writeable = False
z.fill(2)

ValueError: assignment destination is read-only

In [67]:
# part of data or total of data
np.random.seed(0)
np.set_printoptions(threshold=5) #part 超過5個就省略
np.set_printoptions(threshold=sys.maxsize) #total
z = np.random.randint(10,size=(15,15))
print(z)


[[5 0 3 3 7 9 3 5 2 4 7 6 8 8 1]
 [6 7 7 8 1 5 9 8 9 4 3 0 3 5 0]
 [2 3 8 1 3 3 3 7 0 1 9 9 0 4 7]
 [3 2 7 2 0 0 4 5 5 6 8 4 1 4 9]
 [8 1 1 7 9 9 3 6 7 2 0 3 5 9 4]
 [4 6 4 4 3 4 4 8 4 3 7 5 5 0 1]
 [5 9 3 0 5 0 1 2 4 2 0 3 2 0 7]
 [5 9 0 2 7 2 9 2 3 3 2 3 4 1 2]
 [9 1 4 6 8 2 3 0 0 6 0 6 3 3 8]
 [8 8 2 3 2 0 8 8 3 8 2 8 4 3 0]
 [4 3 6 9 8 0 8 5 9 0 9 6 5 3 1]
 [8 0 4 9 6 5 7 8 8 9 2 8 6 6 9]
 [1 6 8 8 3 2 3 6 3 6 5 7 0 8 4]
 [6 5 8 2 3 9 7 5 3 4 5 3 3 7 9]
 [9 9 7 3 2 3 9 7 7 5 1 2 2 8 1]]


In [75]:
# 在一個數組中 找一個最接近一個數的index
z = np.arange(101)
v = np.random.uniform(0,100)
print(z)
print(v)
index = np.abs(z-v).argmin()
print(index)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
17.09865986831315
17


In [76]:
# float32 -> int32
z = np.arange(10,dtype=np.int32)
print(z.dtype)
z = z.astype(np.float32)
print(z.dtype)

int32
float32


In [84]:
# array element indax and value
z = np.random.randint(9,size=(3,3))
print(z)
# for index in z:
#     print(index)
for index,value in np.ndenumerate(z):
    print(index,value)

[[4 0 6]
 [4 2 4]
 [6 3 3]]
(0, 0) 4
(0, 1) 0
(0, 2) 6
(1, 0) 4
(1, 1) 2
(1, 2) 4
(2, 0) 6
(2, 1) 3
(2, 2) 3


In [87]:
# sort by special col
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[7 2 7]
 [1 6 5]
 [0 0 3]]
[[0 0 3]
 [7 2 7]
 [1 6 5]]


In [95]:
# calculate each number
z = np.array([1,2,3,2,1,2,3,5,4,5,2])
print(z)
np.bincount(z)

[1 2 3 2 1 2 3 5 4 5 2]


array([0, 2, 4, 2, 1, 2], dtype=int64)

In [100]:
# sum in last 2D array in 4D array
z = np.random.randint(0,10,(2,3,4,8))
print(z)
res = z.sum(axis=(-2,-1))
res

[[[[2 6 1 3 7 0 5 4]
   [5 5 3 8 0 1 5 4]
   [1 5 0 6 8 8 6 3]
   [4 4 3 6 5 9 8 1]]

  [[3 8 1 5 8 0 3 7]
   [1 7 8 0 7 5 9 9]
   [6 8 7 5 9 1 0 0]
   [5 6 3 6 1 7 7 0]]

  [[7 6 0 4 2 7 5 2]
   [8 5 6 6 4 1 5 4]
   [5 5 6 3 8 1 4 2]
   [9 7 4 1 8 2 3 3]]]


 [[[4 1 6 2 5 4 9 1]
   [5 9 4 5 7 4 4 2]
   [2 1 3 0 1 9 1 6]
   [9 8 6 3 0 7 3 2]]

  [[5 9 7 3 4 7 6 7]
   [3 6 9 3 7 1 3 7]
   [8 8 4 5 3 6 9 6]
   [2 9 3 5 7 9 0 7]]

  [[1 2 5 0 5 8 9 8]
   [2 5 3 1 7 3 8 5]
   [5 1 9 7 2 1 0 1]
   [0 1 1 6 8 8 3 2]]]]


array([[136, 152, 143],
       [133, 178, 127]])

In [103]:
# exchange array's row
z = np.arange(25).reshape(5,5)
print(z)
z[[0,3]] = z[[3,0]]
z

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

In [122]:
# find max count value in array
z = np.random.randint(0,50,10)
print(z)
print(np.bincount(z)) # 只計算非負整數
np.bincount(z).argmax()

[17 17  4 18 17 34  3 29 49 49]
[0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 3 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 2]


17

In [107]:
# quickly find top k
z = np.arange(10000)
np.random.shuffle(z) #洗牌
n = 5
print(z[np.argpartition(-z,n)[:n]])

[9997 9999 9998 9996 9995]


In [124]:
# delete same values(same row) in array 
z = np.random.randint(0,2,(10,3))
print(z)
e = np.all(z[:,1:] == z[:,:-1],axis=1) #切兩半
print(e)
# a = np.array([1,2,3,4])
# b = np.array([1,2,3,5])
# print(np.all(a == b))
# print(np.any(a == b))

[[0 1 1]
 [1 0 0]
 [0 0 1]
 [1 1 0]
 [1 0 1]
 [1 1 1]
 [1 1 0]
 [0 0 1]
 [0 1 1]
 [0 1 0]]
[False False False False False  True False False False False]
