In [1]:
import numpy as np

1. 對ndarray來說，裡面所有的元素必須是同一類型的，如果不是會自動向下轉換

In [8]:
tang_list = [1,2,3,4,5.0] # 必須同類型(維持底層高效性) 否則會做向下轉換
tang_array = np.array(tang_list)
tang_array

array([1., 2., 3., 4., 5.])

In [3]:
type(tang_array)

numpy.ndarray

In [4]:
tang_array.dtype #  each value type of array

dtype('int32')

In [7]:
tang_array.dtype

dtype('float64')

In [9]:
tang_array = np.array([1,2,3,4,5])
tang_array.shape

(5,)

In [10]:
tang_array.size

5

In [13]:
tang_array = np.array([[1,2,3,4,5],[5,6,8,9,2]])
tang_array.size

10

In [14]:
np.shape(tang_array)

(2, 5)

In [15]:
tang_array.ndim # 判斷維度

2

In [16]:
tang_array.fill(0)
tang_array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [54]:
tang_array = np.array([[1,2,3,4,5],[5,6,8,9,2]])
tang_array[0:, 2]  #多維slice 第一個1:2 代表哪一個陣列 第二個2代表這些陣列的哪個位置 取出後放在一個陣列裡

array([3, 8])

In [32]:
tang_array = np.array([[1,2,3,4,5],[5,6,8,9,2]])
tang_array2 = tang_array
tang_array2[1,2] = 100
tang_array2

array([[  1,   2,   3,   4,   5],
       [  5,   6, 100,   9,   2]])

In [33]:
tang_array

array([[  1,   2,   3,   4,   5],
       [  5,   6, 100,   9,   2]])

In [38]:
tang_array3 = tang_array.copy() # deep copy
tang_array3[1,2] = 10000
tang_array3

array([[    1,     2,     3,     4,     5],
       [    5,     6, 10000,     9,     2]])

In [35]:
tang_array

array([[  1,   2,   3,   4,   5],
       [  5,   6, 100,   9,   2]])

In [36]:
tang_array4 = tang_array[:,:]
tang_array4[1,2] = 1
tang_array4

array([[1, 2, 3, 4, 5],
       [5, 6, 1, 9, 2]])

In [37]:
tang_array

array([[1, 2, 3, 4, 5],
       [5, 6, 1, 9, 2]])

In [39]:
tang_array = np.arange(0,100,10)
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
mask = np.array([0,0,0,1,1,1,0,1,0,1],dtype=bool)
mask

array([False, False, False,  True,  True,  True, False,  True, False,
        True])

In [43]:
tang_array[mask] # 是否取值

array([30, 40, 50, 70, 90])

In [44]:
random_array = np.random.rand(10)
random_array

array([0.47619392, 0.52938809, 0.88611266, 0.81798703, 0.78295338,
       0.75306268, 0.61027602, 0.25845639, 0.23988095, 0.15724461])

In [45]:
mask = random_array > 0.5
mask

array([False,  True,  True,  True,  True,  True,  True, False, False,
       False])

In [46]:
tang_array[mask]

array([10, 20, 30, 40, 50, 60])

In [47]:
tang_array = np.array([10,20,30,40,50])
tang_array > 30

array([False, False, False,  True,  True])

In [48]:
np.where(tang_array > 30)

(array([3, 4], dtype=int64),)

In [49]:
tang_array[np.where(tang_array > 30)]

array([40, 50])

In [52]:
tang_array = np.array([[10,20,30,40,50],[10,20,30,40,50]])
tang_array > 30

array([[False, False, False,  True,  True],
       [False, False, False,  True,  True]])

In [53]:
tang_array[np.where(tang_array > 30)]

array([40, 50, 40, 50])

In [2]:
tang_array = np.array([1,10,3.5,'str'], dtype=np.object)
tang_array


array([1, 10, 3.5, 'str'], dtype=object)

In [3]:
tang_array*2

array([2, 20, 7.0, 'strstr'], dtype=object)

In [5]:
tang_array = np.array([1,2,3,4,5]) 
tang_array2 = np.asarray(tang_array,dtype=np.float32) # 不改變原始結構 要使用需要再賦值
tang_array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [6]:
tang_array

array([1, 2, 3, 4, 5])

In [7]:
tang_array.astype(np.float32) # 不改變原始結構

array([1., 2., 3., 4., 5.], dtype=float32)

In [8]:
tang_array = np.array([np.arange(0,100,10),np.arange(0,200,20)])
tang_array

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [  0,  20,  40,  60,  80, 100, 120, 140, 160, 180]])