In [1]:
import numpy as np

In [36]:
tang_array = np.array([[1,2,3],[4,5,6]])

In [3]:
np.sum(tang_array)

21

In [4]:
np.sum(tang_array, axis=0) # 指定操作維度

array([5, 7, 9])

In [5]:
np.sum(tang_array, axis=1)

array([ 6, 15])

In [8]:
np.sum(tang_array, axis=-1)

array([ 6, 15])

In [15]:
tang_array.sum() # 累加

21

In [11]:
tang_array.sum(axis=0)

array([5, 7, 9])

In [16]:
tang_array.prod() # 乘積

720

In [13]:
tang_array.prod(axis=0)

array([ 4, 10, 18])

In [14]:
tang_array.prod(axis=1)

array([  6, 120])

In [18]:
tang_array.min() # 最小值

1

In [19]:
tang_array.min(axis=1)

array([1, 4])

In [21]:
tang_array.max() # 最大值

6

In [22]:
tang_array.max(axis=1)

array([3, 6])

In [23]:
tang_array.argmin() # 最小值位置

0

In [24]:
tang_array.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [25]:
tang_array.argmin(axis=1)

array([0, 0], dtype=int64)

In [26]:
tang_array.argmax() # 最大值位置

5

In [27]:
tang_array.mean() # 平均數

3.5

In [28]:
tang_array.mean(axis=1)

array([2., 5.])

In [29]:
tang_array.mean(axis=0)

array([2.5, 3.5, 4.5])

In [30]:
tang_array

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
tang_array.std()  # 標準差

2.1147629234082537

In [34]:
tang_array.var() # 方差

4.472222222222223

In [37]:
tang_array 

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
tang_array.clip(2,5) # 小於2的都會變成2 大於5的都會變成5

array([[2, 2, 3],
       [4, 5, 5]])

In [40]:
tang_array = np.array([1.2,3.56,6.41])

In [41]:
tang_array.round() #4捨5入

array([1., 4., 6.])

In [42]:
tang_array.round(decimals=1) #4捨5入 在小數點後位置

array([1.2, 3.6, 6.4])

In [7]:
np.random.seed(0)
array1 = np.random.randint(1,10,(2,2,2))
print(array1)
print('---------')
print(array1.sum(axis=2))
print('---------')
print(array1.sum(axis=1))
print('---------')
print(array1.sum(axis=0))

[[[6 1]
  [4 4]]

 [[8 4]
  [6 3]]]
---------
[[ 7  8]
 [12  9]]
---------
[[10  5]
 [14  7]]
---------
[[14  5]
 [10  7]]
