In [1]:
import numpy as np

In [19]:
tang_array = np.array([[1.5,1.3,7.5],[5.6,7.8,1.2]])
tang_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [20]:
np.sort(tang_array)

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [21]:
np.sort(tang_array,axis=0)

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

In [22]:
tang_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [23]:
np.argsort(tang_array) # 最小的位置 (axis=1)

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [24]:
np.argsort(tang_array,axis=0)

array([[0, 0, 1],
       [1, 1, 0]], dtype=int64)

In [25]:
tang_array = np.linspace(0,10,10) # 返回指定間隔內均勻間隔的數字
tang_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [26]:
values = np.array([2.5,6.5,9.5]) 
np.searchsorted(tang_array,values) # 不知道要將數字插入到該array的位置 可使用 第一個位置需要排序好的數組

array([3, 6, 9], dtype=int64)

In [27]:
tang_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [28]:
a = np.array([[1,0,6],[1,7,0],[2,3,1],[4,3,0]])
a

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [4, 3, 0]])

In [29]:
index = np.lexsort([-1*a[:,0],a[:,2]]) # a[:,0] 是降序 a[:,2]是升序 先根據後面的 -1代表降序
index

array([3, 1, 2, 0], dtype=int64)

In [16]:
tang_array = a[index]
tang_array

array([[4, 3, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])