In [1]:
import numpy as np


In [5]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
tang_array.shape

(10,)

In [7]:
tang_array.shape = 2,5 #相乘要 == size 
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
tang_array.shape = 1,10 #有,會產生二維陣列
tang_array

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [3]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
tang_array = tang_array[np.newaxis,:]
print(tang_array)
print(np.newaxis)

[[[0 1 2 3 4 5 6 7 8 9]]]
None


In [11]:
tang_array = np.arange(10)
tang_array = tang_array[:,np.newaxis]
tang_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [12]:
tang_array = tang_array[:,np.newaxis,np.newaxis]
tang_array.shape

(10, 1, 1, 1)

In [13]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
tang_array.shape = 10,1,1,1 
tang_array

array([[[[0]]],


       [[[1]]],


       [[[2]]],


       [[[3]]],


       [[[4]]],


       [[[5]]],


       [[[6]]],


       [[[7]]],


       [[[8]]],


       [[[9]]]])

In [15]:
tang_array = tang_array.squeeze() # 壓縮 將空的軸(裡面是1的)去掉
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
tang_array.shape = 2,5
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
tang_array.transpose() # 原始不變

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [27]:
tang_array.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [28]:
a = np.array([[1,2,3],[32,56,85]])
b = np.array([[15,82,43],[312,5206,185]])

In [29]:
c = np.concatenate((a,b)) # 默認第一個維度拼接
c

array([[   1,    2,    3],
       [  32,   56,   85],
       [  15,   82,   43],
       [ 312, 5206,  185]])

In [30]:
c = np.concatenate((a,b),axis=1)
c

array([[   1,    2,    3,   15,   82,   43],
       [  32,   56,   85,  312, 5206,  185]])

In [31]:
c.shape

(2, 6)

In [32]:
np.vstack((a,b))

array([[   1,    2,    3],
       [  32,   56,   85],
       [  15,   82,   43],
       [ 312, 5206,  185]])

In [33]:
np.hstack((a,b))

array([[   1,    2,    3,   15,   82,   43],
       [  32,   56,   85,  312, 5206,  185]])

In [34]:
a.flatten()

array([ 1,  2,  3, 32, 56, 85])

In [35]:
a

array([[ 1,  2,  3],
       [32, 56, 85]])

In [36]:
a.ravel()

array([ 1,  2,  3, 32, 56, 85])

In [37]:
a

array([[ 1,  2,  3],
       [32, 56, 85]])