In [1]:
import numpy as np

In [4]:
x = np.array([5,5,3])
y = np.array([2,2,2])

In [51]:
print(np.multiply(x,y)) # element-wise
print(x*y)

[10 10  6]
[10 10  6]


In [35]:
np.dot(x,y) # 2*5 + 2*5 + 3*2 維度要相同

26

In [36]:
x.shape

(3,)

In [37]:
y.shape

(3,)

In [5]:
x.shape = 3,1
x

array([[5],
       [5],
       [3]])

In [7]:
y.shape = 1,3
y

array([[2, 2, 2]])

In [8]:
print(x)
print(y)
print(x.shape)
print(y.shape)
np.dot(x,y) 

[[5]
 [5]
 [3]]
[[2 2 2]]
(3, 1)
(1, 3)


array([[10, 10, 10],
       [10, 10, 10],
       [ 6,  6,  6]])

In [41]:
np.dot(y,x)

array([[26]])

In [48]:
x = np.array([[2,5,3],[7,3,6]])
y = np.array([[4,2],[3,6],[8,7]])
print(x.shape)
print(y.shape)
print(np.dot(x,y))
print(np.dot(y,x))

(2, 3)
(3, 2)
[[47 55]
 [85 74]]
[[22 26 24]
 [48 33 45]
 [65 61 66]]


In [16]:
x = np.array([1,1,1])
y = np.array([[1,2,3],[4,5,6]])
print(x*y)

[[1 2 3]
 [4 5 6]]


In [18]:
x = np.array([1,1,1,4]) # shape要一樣
y = np.array([1,1,1,2])
x == y

array([ True,  True,  True, False])

In [19]:
np.logical_and(x,y)

array([ True,  True,  True,  True])

In [20]:
np.logical_or(x,y)

array([ True,  True,  True,  True])

In [21]:
np.logical_not(x,y)

array([0, 0, 0, 0])

In [52]:
x = np.array([1,1,1,0]) 
y = np.array([1,1,1,2])
np.logical_and(x,y)

array([ True,  True,  True, False])

In [57]:
x = np.random.randint(10,size=(2,4))
y = np.random.randint(10,size=(4,2))
print(x)
print(y)  #57

[[7 4 5 2]
 [8 1 8 4]]
[[1 2]
 [1 3]
 [8 3]
 [3 8]]


In [58]:
x.dot(y)

array([[57, 57],
       [85, 75]])