In [1]:
import numpy as np

In [2]:
np.random.rand(3,2)

array([[0.63237862, 0.01041821],
       [0.46365241, 0.85080529],
       [0.67968174, 0.17524171]])

In [4]:
np.random.randint(9,size=(4,5)) # 左閉右開區間

array([[4, 6, 8, 2, 2],
       [2, 6, 8, 0, 2],
       [0, 7, 6, 7, 5],
       [0, 1, 4, 2, 0]])

In [5]:
np.random.rand()

0.3348311410718394

In [6]:
np.random.random_sample()

0.07626458514530865

In [8]:
np.random.randint(0,10,3) #可重複

array([0, 7, 7])

In [9]:
mu, sigma = 0, 0.1
np.random.normal(mu, sigma,10) # 高斯分布

array([ 0.01798965,  0.11885095,  0.02919996, -0.14045319, -0.02688607,
       -0.03614628, -0.09437849,  0.14199015,  0.12296976, -0.04950164])

In [10]:
np.set_printoptions(precision=3)

In [11]:
np.random.normal(mu, sigma,10)

array([-0.073,  0.106, -0.04 ,  0.052, -0.021, -0.107, -0.036, -0.124,
        0.017,  0.008])

In [13]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.random.shuffle(tang_array) #洗牌 不回傳值
tang_array

array([2, 6, 0, 3, 8, 1, 7, 9, 4, 5])

In [38]:
np.random.seed(0) # 固定隨機 隨機前使用
mu, sigma = 0, 0.1
np.random.normal(mu, sigma,10)

array([ 0.176,  0.04 ,  0.098,  0.224,  0.187, -0.098,  0.095, -0.015,
       -0.01 ,  0.041])

In [48]:
np.random.normal(mu, sigma,10)

array([ 0.188, -0.135, -0.127,  0.097, -0.117,  0.194, -0.041, -0.075,
        0.192,  0.148])