In [1]:
import numpy as np

In [11]:
# np.random.seed(0)
# tang_array = np.random.randint(10,size=(2,5))
string = '''1 2 3 4 5 
6 7 8 9 10'''
with open('test.txt',mode='w') as f:
    f.write(string)

In [13]:
tang_array = []
with open('test.txt') as f:
    for line in f:
        fileds = line.split()
        data = [float(i) for i in fileds]
        tang_array.append(data)
tang_array = np.array(tang_array)
tang_array

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [14]:
data = np.loadtxt('test.txt')
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [15]:
string = '''1,2,3,4,5
6,7,8,9,10'''
with open('test2.txt',mode='w') as f:
    f.write(string)

In [17]:
data = np.loadtxt('test2.txt',delimiter=',') # 分割符
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [19]:
string = '''x,y,z,a,b
1,2,3,4,5
6,7,8,9,10'''
with open('test3.txt',mode='w') as f:
    f.write(string)

In [21]:
data = np.loadtxt('test3.txt',delimiter=',',skiprows=1) # delete first row
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [23]:
string = '''x,y,z,a,b
1,2,3,4,5
6,7,8,9,10
8,7,8,6,4
5,3,7,8,9
2,6,5,7,8'''
with open('test4.txt',mode='w') as f:
    f.write(string)
data = np.loadtxt('test4.txt',delimiter=',',skiprows=1,usecols=(1,3,4)) # point specific col
data

array([[ 2.,  4.,  5.],
       [ 7.,  9., 10.],
       [ 7.,  6.,  4.],
       [ 3.,  8.,  9.],
       [ 6.,  7.,  8.]])

In [29]:
tang_array = np.random.randint(10,size=(3,3))
np.savetxt('test5.txt',tang_array,fmt="%d",delimiter=',') # fmt:save format %d整數

In [30]:
tang_array = np.random.randint(10,size=(3,3))
np.savetxt('test5.txt',tang_array,fmt="%.2f",delimiter=',') # fmt:save format %.2f 2位float

### array structure write and read

In [31]:
tang_array = np.random.randint(20,size=(3,3))
np.save('test_arr.npy',tang_array)

In [32]:
np.load('test_arr.npy')

array([[11,  4,  6],
       [ 4, 15,  3],
       [12,  4,  8]])

In [33]:
tang_array2 = np.random.randint(10,size=(3,3))
tang_array2

array([[4, 3, 7],
       [5, 5, 0],
       [1, 5, 9]])

In [42]:
np.savez('test1_arr.npz',c=tang_array,b=tang_array2) # 壓縮檔

In [43]:
np.load('test1_arr.npz') # a dict

In [44]:
np.load('test1_arr.npz')['c']

array([[11,  4,  6],
       [ 4, 15,  3],
       [12,  4,  8]])